#!/usr/bin/env node

var program = require('commander');

program.usage('<catalogPath> <columnPath> <propertyPath|command> <value>');

program.parse(process.argv);

var args = program.args;

if (!args.length)
  program.help();