#!/usr/bin/env node
var chalk = require('chalk');
var program = require('commander');

program
	.usage('[catalogPath [columnPath]]')
	.parse(process.argv);

// Max number of args to 'list' a config
var args = program.args.slice(0, 3);

/**
 * PanaxJS call
 */
var Panax = require('../panaxjs');
var panax_config = require('./config/panax');
var oPanax = new Panax(panax_config);

oPanax.tableConfig(args, function (err, lines) {
	if(err) {
		console.error('Error: ' + err);
		process.exit(1);
	}
	if(!lines.length) {
		console.warn('Warning: No results for given arguments:\n\n\t'+args.join(', '));
		process.exit(9);
	}

	lines.forEach(function (line, idx) {
		line = line['propertyString'].split(' ').slice(2).join(' ').split(', ');
		console.log(idx + '\t' +
			chalk.bold.white(line[0]) + ', ' +
			chalk.green(line[1]) + ', ' +
			chalk.blue(line[2]) + ', ' +
			line[3]
			);
	});

	process.exit(0);
});