#!/usr/bin/env node

var program = require('commander');

program
	.command('add', 'Add configuration')
	.command('remove', 'Remove configuration')
	.command('list', 'List configuration(s)')
	.parse(process.argv);

if (!process.argv.slice(2).length) {
  program.help();
}