#!/usr/bin/env node

var program = require('commander');

program
	.usage('<catalogPath> <columnPath> <propertyPath|command>')
	.parse(process.argv);

var args = program.args;

if (!args.length)
  program.help();