#!/usr/bin/env node

var chalk = require('chalk');
var program = require('commander');

program
	.usage('<catalogPath> <columnPath> <propertyPath|command> <value>')
	.parse(process.argv);

// 4 = Min number of args to 'add' a config
var args = program.args;
if (args.length != 4)
  program.help();

/**
 * PanaxJS call
 */
var Panax = require('../panaxjs');
var panax_config = require('./config/panax');
var oPanax = new Panax(panax_config);

oPanax.tableConfig(args, function (err, response) {
	if(err) {
		console.error(chalk.red('Error: ') + err);
		process.exit(1);
	}

	console.log(chalk.bold.green('ADD') + ':\t' +
		chalk.bold.white('\'' + args[0] + '\'') + ', ' +
		chalk.blue('\'' + args[1] + '\'') + ', ' +
		chalk.cyan('\'' + args[2] + '\'') + ', ' +
		'\'' + args[3] + '\''
	);

	process.exit(0);
});