#!/usr/bin/env node

var chalk = require('chalk');
var program = require('commander');

program
	.usage('<entityPath> <columnPath> <propertyPath|command>')
	.parse(process.argv);

// 3 = Min number of args to 'remove' a config
var args = program.args;
if (args.length != 3)
  program.help();

/**
 * PanaxJS call
 */
var Panax = require('panaxjs');
var panax_config = require('./config/panax');
var oPanax = new Panax(panax_config);

oPanax.clearConfig(args, function (err, response) {
	if(err) {
		console.error(chalk.red('Error: ') + err);
		process.exit(1);
	}

	console.log(chalk.bold.red('REMOVE') + ':\t' +
		chalk.bold.white('\'' + args[0] + '\'') + ', ' +
		chalk.blue('\'' + args[1] + '\'') + ', ' +
		chalk.cyan('\'' + args[2] + '\'')
	);

	process.exit(0);
});